<!-- Module 1 -->
<div class="col-md-12">
  <h2>Module 1 <small>Basic Hiragana</small></h2>
  <hr/>
</div>


<!-- Level 1 -->
<?php echo renderView('index/partials/mod1/level-1.phtml'); ?>

<!-- Level 2 -->
<?php echo renderView('index/partials/mod1/level-2.phtml'); ?>

<!-- Level 3 -->
<?php echo renderView('index/partials/mod1/level-3.phtml'); ?>

<!-- Level 4 -->
<?php echo renderView('index/partials/mod1/level-4.phtml'); ?>


<!-- Module 2 -->
<div class="col-md-12">
  <h2>Module 2 <small>Complete Hiragana</small></h2>
  <hr/>
</div>

<!-- Level 1 -->
<?php echo renderView('index/partials/mod2/level-1.phtml'); ?>

<!-- Level 2 -->
<?php echo renderView('index/partials/mod2/level-2.phtml'); ?>

<!-- Level 3 -->
<?php echo renderView('index/partials/mod2/level-3.phtml'); ?>

<!-- Level 4 -->
<?php echo renderView('index/partials/mod2/level-4.phtml'); ?>

<!-- Level 5 -->
<?php echo renderView('index/partials/mod2/level-5.phtml'); ?>

<!-- Level 6 -->
<?php echo renderView('index/partials/mod2/level-6.phtml'); ?>
