<!-- /////////////////////////////////////////////////// -->
<!-- ///    ////    //      //     //////     ////////// -->
<!-- ///  /  //  /  //  //  //  ///  ///  //  ////////// -->
<!-- ///  //  ////  //  //  //  ///  ///////  ////////// -->
<!-- ///  ////////  //  //  //  ///  ///////  ////////// -->
<!-- ///  ////////  //      //     ////          //  /// -->
<!-- /////////////////////////////////////////////////// -->

<div class="col-md-12">
  <h2>Module 1 <small>Basic Hiragana</small></h2>
  <hr/>
</div>

<!-- Level 1 -->
<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 1 <small>Nice to meet you!</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod1Level1">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod1Level1">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <h4>
            Hiragana Sounds (basic)
            <br/>
            <small>
              The first step to learn japanese is to recognize the hiragana symbols
              and know that each one have a specific sound. Take a look one by one,
              try to speak and write a lot. Take your own time to it.
            </small>
          </h4>
          <hr/>
          <div class="row" style="font-size: 72pt; text-align: center;">
            <div class="col-xs-5" id="m1level1-h" style="min-height: 150px;"></div>
            <div class="col-xs-2" style="min-height: 150px; line-height: 150px;">=</div>
            <div class="col-xs-5" id="m1level1-s" style="min-height: 150px;"></div>
            <hr/>

            <div class="col-xs-6"><button type="button" id="btn-m1level1-prev" class="btn btn-success"><i class="fa fa-backward"></i> Previous</button></div>
            <div class="col-xs-6"><button type="button" id="btn-m1level1-next" class="btn btn-success">Next <i class="fa fa-forward"></i></button></div>

          </div><!-- /.row -->
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>
<!-- /Level 1 -->
















<!-- Level 2 -->
<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 2 <small>Guess who?</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod1Level2">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod1Level2">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <h4>
            Practice Hiragana Sounds (Romaji)
            <br/>
            <small>
              Now that you already know the basic hiragana symbols, let's practice their sounds. To these "sounds"
              we call <i>Romaji</i>.
            </small>
          </h4>
          <hr/>
          <div class="thumbnail question guess-who" id="mod1level2-question"></div>
          <div class="row" id="mod1level2-answer">
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="0"></span></div>
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="1"></span></div>
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="2"></span></div>
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="3"></span></div>
          </div><!-- /.row -->

          <div class="row">
            <div class="col-xs-12 text-right">Score: <span id="mod1level2-pnts">0</span></div>
          </div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>
<!-- /Level 2 -->

















<!-- Level 3 -->
<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 3 <small>Do you know me?</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1 Hiragana">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod1Level3">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod1Level3">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <h4>
            Romaji to Hiragana
            <br/>
            <small>
              If you came to here, you must to be able to recognize all basics hiragana to read speak and write.
              This exercise gives you enough skills to begin with words. Go on to the next exercise only when you
              are able to recognize all hiragana basic symbols, so you will can know some awesome words.
            </small>
          </h4>
          <div class="thumbnail question know-me" id="mod1level3-question"></div>
          <div class="input-group">
            <span class="input-group-addon">Romaji</span>
            <input type="text" class="form-control" name="mod1level3-answere" id="mod1level3-answere" placeholder="Insert your answere" />
          </div>
          <hr/>
          <div class="row">
            <div class="col-xs-9">
              <table class="table table-bordered table-tips" id="mod1level3-table-tips">
                <tr>
                  <td data-key="0"></td>
                  <td data-key="1"></td>
                  <td data-key="2"></td>
                  <td data-key="3"></td>
                </tr>
              </table>
            </div>
            <div class="col-xs-3">
              <button type="button" id="mod1level3-btn-tips" class="btn btn-danger pull-right">
                <i class="fa fa-comments"></i> Tips
              </button>
            </div>
          </div><!-- /.row -->

          <div class="row">
            <div class="col-xs-12 text-right">Score: <span id="mod1level3-pnts">0</span></div>
          </div><!-- /.row -->
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>
<!-- Fim do Level 3 -->











<!-- Level 4 -->
<!--
JP Ref.
http://www.learn-japanese-adventure.com/common-japanese-phrases.html
https://www.nhk.or.jp/lesson/portuguese/
-->
<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 4 <small>Some words</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod1Level4">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod1Level4">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <h4>
            Find the Romaji
            <br/>
            <small>
              You will know some sentences written in japanese and it's meaning, just find out how to pronounce it
              with Romaji, practice as much as you can, after ahead things will be a little more difficult.
            </small>
          </h4>
          <div class="thumbnail words tcenter" id="mod1level4-question" style="font-size: 36pt;">
            <p id="mod1level4-question-mean"></p>
            <hr/>
            <p id="mod1level4-question-hiragana"></p>
            <hr/>
            <p id="mod1level4-question-romaji"></p>
          </div>
          <div class="input-group">
            <span class="input-group-addon">Romaji</span>
            <input type="text" class="form-control tcenter" id="mod1level4-answere" placeholder="Insert your answere" />
          </div>
          <br/>
          <button type="button" class="btn btn-danger btn-xs pull-right" id="mod1level4-btn-tips"><i class="fa fa-comments"></i> Tips</button>
          <div class="clearfix"></div>
          <div class="row" id="mod1level4-tips" style="display: none; text-align: center;"></div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>
<!-- /Level 4 -->







<!-- /////////////////////////////////////////////////// -->
<!-- ///    ////    //      //     //////     ////////// -->
<!-- ///  /  //  /  //  //  //  ///  ///  //  ////////// -->
<!-- ///  //  ////  //  //  //  ///  /////  //////////// -->
<!-- ///  ////////  //  //  //  ///  ///  ////////////// -->
<!-- ///  ////////  //      //     ////      //  /////// -->
<!-- /////////////////////////////////////////////////// -->


<div class="col-md-12">
  <h2>Module 2 <small>Complete Hiragana</small></h2>
  <hr/>
</div>

<!-- Module 2 - Level 1 -->
<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 1 <small>Some more Romaji's</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod2Level1">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod2Level1">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">

          <h4>
            Adding to the known
            <br/>
            <small>
              Some known hiragana symbols can be increased to give more options of sounds (romaji).
              Practice it and after that you will be able to read whatever word with hiragana.
            </small>
          </h4>
          <div class="row">
            <div class="col-md-12">
              Hiragana:
              <div class="thumbnail question" id="mod2level1-question"></div>
            </div>
            <div class="col-md-12">
              Romaji:
              <div class="thumbnail tcenter" id="mod2level1-romaji" style="font-size: 42pt;"></div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-6" style="text-align: center;">
              <button class="btn btn-success" id="m2lvl1-prev"><i class="fa fa-backward"></i> Previous</button>
            </div>
            <div class="col-xs-6" style="text-align: center;">
              <button class="btn btn-success" id="m2lvl1-next"><i class="fa fa-forward"></i> Next</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!-- /.modal -->
</div>












<!-- Module 2 - Level 2 -->
<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 2 <small>Join together</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod2Level2">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod2Level2">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">

          <h4>
            New Romaji with join ya, yu and yo
            <br/>
            <small>
              When you join smaller や(ya), ゆ(yu) and よ(yo) after some romaji's you get new possibilities.
              There is others combinations we will not talk about for while because is not so common.
            </small>
          </h4>
          <div class="thumbnail question" id="mod2level2-question"></div>
          <div class="row">
            <div class="col-xs-6" style="text-align: center;">
              <button class="btn btn-success" id="m2lvl2-prev"><i class="fa fa-backward"></i> Previous</button>
            </div>
            <div class="col-xs-6" style="text-align: center;">
              <button class="btn btn-success" id="m2lvl2-next"><i class="fa fa-forward"></i> Next</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!-- /.modal -->
</div>







<!-- Module 2 - Level 3 -->
<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 3 <small>Guess who?</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod2Level3">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod2Level3">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">

          <h4>
            Practice Hiragana Sounds (Romaji)
            <br/>
            <small>
              Now that you already know all hiragana symbols, let's practice their sounds (romaji).
            </small>
          </h4>

          <div class="thumbnail question guess-who" id="mod2level3-question"></div>
          <div class="row" id="mod2level3-answer">
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="0"></span></div>
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="1"></span></div>
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="2"></span></div>
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="3"></span></div>
          </div><!-- /.row -->

          <div class="row">
            <div class="col-xs-12 text-right">Score: <span id="mod2level3-pnts">0</span></div>
          </div>

        </div><!-- /.modal-body -->
      </div>
    </div>
  </div><!-- /.modal -->
</div>





<!-- Level 4 -->
<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 4 <small>Do you know me?</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1 Hiragana">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod2Level4">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod2Level4">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <h4>
            Romaji to Hiragana
            <br/>
            <small>
              If you came to here, you must to be able to recognize all basics hiragana to read speak and write.
              This exercise gives you enough skills to begin with words. Go on to the next exercise only when you
              are able to recognize all hiragana basic symbols, so you will can know some awesome words.
            </small>
          </h4>
          <div class="thumbnail question know-me" id="mod2level4-question"></div>
          <div class="input-group">
            <span class="input-group-addon">Romaji</span>
            <input type="text" class="form-control tcenter" name="mod2level4-answere" id="mod2level4-answere" placeholder="Insert your answere" />
          </div>
          <hr/>
          <div class="row">
            <div class="col-xs-9">
              <table class="table table-bordered table-tips" id="mod2level4-table-tips">
                <tr>
                  <td data-key="0"></td>
                  <td data-key="1"></td>
                  <td data-key="2"></td>
                  <td data-key="3"></td>
                </tr>
              </table>
            </div>
            <div class="col-xs-3">
              <button type="button" id="mod2level4-btn-tips" class="btn btn-danger pull-right">
                <i class="fa fa-comments"></i> Tips
              </button>
            </div>
          </div><!-- /.row -->

          <div class="row">
            <div class="col-xs-12 text-right">Score: <span id="mod2level4-pnts">0</span></div>
          </div><!-- /.row -->
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>
<!-- Fim do Level 4 -->








<!-- Module 2 - Level 5 -->
<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 5 <small>Reverse guess who?</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod2Level5">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod2Level5">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">

          <h4>
            Practice Hiragana Sounds, reverse (Romaji)
            <br/>
            <small>
              Now that you already know all hiragana symbols, let's practice their sounds (romaji).
            </small>
          </h4>

          <div class="thumbnail question guess-who" id="mod2level5-question"></div>
          <div class="row" id="mod2level5-answer">
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="0"></span></div>
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="1"></span></div>
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="2"></span></div>
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="3"></span></div>
          </div><!-- /.row -->

          <div class="row">
            <div class="col-xs-12 text-right">Score: <span id="mod2level5-pnts">0</span></div>
          </div>

        </div><!-- /.modal-body -->
      </div>
    </div>
  </div><!-- /.modal -->
</div>




<!-- Level 6 -->
<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 6 <small>Some words</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod2Level6">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod2Level6">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <h4>
            Find the Romaji
            <br/>
            <small>
              You will know some words written in japanese and it's meaning, just find out how to pronounce it
              with Romaji, practice as much as you can, next one will be about complete phrases.
            </small>
          </h4>
          <div class="well well-sm">
            <i class="fa fa-info"></i> At first we won't show the hiragana symbols to force your memory,
            but when you can't remember any way, just press <i>back space</i> to show it.
          </div>
          <div class="thumbnail words tcenter" id="mod2level6-question" style="font-size: 16pt;">
            <p id="mod2level6-question-mean"></p>
            <hr/>
            <p id="mod2level6-question-hiragana"></p>
            <hr/>
            <p id="mod2level6-question-romaji"></p>
          </div>
          <div class="input-group">
            <span class="input-group-addon">Romaji</span>
            <input type="text" class="form-control tcenter" id="mod2level6-answere" placeholder="Insert your answere" />
          </div>
          <br/>
          <button type="button" class="btn btn-danger btn-xs pull-right" id="mod2level6-btn-tips"><i class="fa fa-comments"></i> Tips</button>
          <div class="clearfix"></div>
          <div class="row" id="mod2level6-tips" style="display: none; text-align: center;"></div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>
<!-- Level 6 -->