<script type="text/javascript" src="assets/js/mod2/level-1.js"></script>

<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 1 <small>Some more Romaji's</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod2Level1">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod2Level1">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">

          <h4>
            Adding to the known
            <br/>
            <small>
              Some known hiragana symbols can be increased to give more options of sounds (romaji).
              Practice it and after that you will be able to read whatever word with hiragana.
            </small>
          </h4>
          <div class="row">
            <div class="col-md-12">
              Hiragana:
              <div class="thumbnail question" id="mod2level1-question"></div>
            </div>
            <div class="col-md-12">
              Romaji:
              <div class="thumbnail tcenter" id="mod2level1-romaji" style="font-size: 42pt;"></div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-6" style="text-align: center;">
              <button class="btn btn-success" id="m2lvl1-prev"><i class="fa fa-backward"></i> Previous</button>
            </div>
            <div class="col-xs-6" style="text-align: center;">
              <button class="btn btn-success" id="m2lvl1-next"><i class="fa fa-forward"></i> Next</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!-- /.modal -->
</div>
