<script type="text/javascript" src="assets/js/mod2/level-2.js"></script>

<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 2 <small>Join together</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod2Level2">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod2Level2">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">

          <h4>
            New Romaji with join ya, yu and yo
            <br/>
            <small>
              When you join smaller や(ya), ゆ(yu) and よ(yo) after some romaji's you get new possibilities.
              There is others combinations we will not talk about for while because is not so common.
            </small>
          </h4>
          <div class="thumbnail question" id="mod2level2-question"></div>
          <div class="row">
            <div class="col-xs-6" style="text-align: center;">
              <button class="btn btn-success" id="m2lvl2-prev"><i class="fa fa-backward"></i> Previous</button>
            </div>
            <div class="col-xs-6" style="text-align: center;">
              <button class="btn btn-success" id="m2lvl2-next"><i class="fa fa-forward"></i> Next</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!-- /.modal -->
</div>

