<script type="text/javascript" src="assets/js/mod2/level-5.js"></script>

<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 5 <small>Reverse guess who?</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod2Level5">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod2Level5">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">

          <h4>
            Practice Hiragana Sounds, reverse (Romaji)
            <br/>
            <small>
              Now that you already know all hiragana symbols, let's practice their sounds (romaji).
            </small>
          </h4>

          <div class="thumbnail question guess-who" id="mod2level5-question"></div>
          <div class="row" id="mod2level5-answer">
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="0"></span></div>
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="1"></span></div>
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="2"></span></div>
            <div class="col-xs-6"><span class="thumbnail point-answer" data-key="3"></span></div>
          </div><!-- /.row -->

          <div class="row">
            <div class="col-xs-12 text-right">Score: <span id="mod2level5-pnts">0</span></div>
          </div>

        </div><!-- /.modal-body -->
      </div>
    </div>
  </div><!-- /.modal -->
</div>
