<script type="text/javascript" src="assets/js/mod2/level-4.js"></script>

<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 4 <small>Do you know me?</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1 Hiragana">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod2Level4">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod2Level4">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <h4>
            Romaji to Hiragana
            <br/>
            <small>
              If you came to here, you must to be able to recognize all basics hiragana to read speak and write.
              This exercise gives you enough skills to begin with words. Go on to the next exercise only when you
              are able to recognize all hiragana basic symbols, so you will can know some awesome words.
            </small>
          </h4>
          <div class="thumbnail question know-me" id="mod2level4-question"></div>
          <div class="input-group">
            <span class="input-group-addon">Romaji</span>
            <input type="text" class="form-control tcenter" name="mod2level4-answere" id="mod2level4-answere" placeholder="Insert your answere" />
          </div>
          <hr/>
          <div class="row">
            <div class="col-xs-9">
              <table class="table table-bordered table-tips" id="mod2level4-table-tips">
                <tr>
                  <td data-key="0"></td>
                  <td data-key="1"></td>
                  <td data-key="2"></td>
                  <td data-key="3"></td>
                </tr>
              </table>
            </div>
            <div class="col-xs-3">
              <button type="button" id="mod2level4-btn-tips" class="btn btn-danger pull-right">
                <i class="fa fa-comments"></i> Tips
              </button>
            </div>
          </div><!-- /.row -->

          <div class="row">
            <div class="col-xs-12 text-right">Score: <span id="mod2level4-pnts">0</span></div>
          </div><!-- /.row -->
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>
