<script type="text/javascript" src="assets/js/mod1/level-1.js"></script>

<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 1 <small>Nice to meet you!</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod1Level1">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod1Level1">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <h4>
            Hiragana Sounds (basic)
            <br/>
            <small>
              The first step to learn japanese is to recognize the hiragana symbols
              and know that each one have a specific sound. Take a look one by one,
              try to speak and write a lot. Take your own time to it.
            </small>
          </h4>
          <hr/>
          <div class="row" style="font-size: 72pt; text-align: center;">
            <div class="col-xs-5" id="m1level1-h" style="min-height: 150px;"></div>
            <div class="col-xs-2" style="min-height: 150px; line-height: 150px;">=</div>
            <div class="col-xs-5" id="m1level1-s" style="min-height: 150px;"></div>
            <hr/>

            <div class="col-xs-6"><button type="button" id="btn-m1level1-prev" class="btn btn-success"><i class="fa fa-backward"></i> Previous</button></div>
            <div class="col-xs-6"><button type="button" id="btn-m1level1-next" class="btn btn-success">Next <i class="fa fa-forward"></i></button></div>

          </div><!-- /.row -->
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>
