<script type="text/javascript" src="assets/js/mod1/level-4.js"></script>

<!--
JP Ref.
http://www.learn-japanese-adventure.com/common-japanese-phrases.html
https://www.nhk.or.jp/lesson/portuguese/
-->
<div class="col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Level 4 <small>Some words</small></h4>
      <hr/>
      <a class="thumbnail">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/250x250/auto" alt="Level 1">
      </a>
      <button type="button" class="btn btn-fullsize btn-success" data-toggle="modal" data-target="#modalMod1Level4">
        <i class="fa fa-play"></i> Começar
      </button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modalMod1Level4">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <h4>
            Find the Romaji
            <br/>
            <small>
              You will know some sentences written in japanese and it's meaning, just find out how to pronounce it
              with Romaji, practice as much as you can, after ahead things will be a little more difficult.
            </small>
          </h4>
          <div class="thumbnail words tcenter" id="mod1level4-question" style="font-size: 36pt;">
            <p id="mod1level4-question-mean"></p>
            <hr/>
            <p id="mod1level4-question-hiragana"></p>
            <hr/>
            <p id="mod1level4-question-romaji"></p>
          </div>
          <div class="input-group">
            <span class="input-group-addon">Romaji</span>
            <input type="text" class="form-control tcenter" id="mod1level4-answere" placeholder="Insert your answere" />
          </div>
          <br/>
          <button type="button" class="btn btn-danger btn-xs pull-right" id="mod1level4-btn-tips"><i class="fa fa-comments"></i> Tips</button>
          <div class="clearfix"></div>
          <div class="row" id="mod1level4-tips" style="display: none; text-align: center;"></div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>
